# Generated by Django 3.2.3 on 2021-06-27 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Pais')),
                ('nombrePais', models.CharField(max_length=50, verbose_name='Nombre de Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut del Colaborador')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Foto de Colaborador')),
                ('nomCompleto', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('fono', models.IntegerField(verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('mail', models.CharField(max_length=50, verbose_name='Nombre completo')),
                ('contrasena', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CaosNews.pais', verbose_name='Pais')),
            ],
        ),
    ]
