# Generated by Django 3.2.3 on 2021-06-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='mail',
            field=models.CharField(max_length=50, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut del Colaborador'),
        ),
    ]
