# Generated by Django 3.2.3 on 2021-06-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaosNews', '0002_auto_20210627_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='pais',
            field=models.CharField(max_length=50, verbose_name='Pais'),
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
